package Game;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Game.USER;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HOME
 */
public class Registre extends javax.swing.JFrame {

    /**
     * Creates new form Registre
     */
    public Registre() {
        initComponents();
        this.setSize(477, 366);
        this.setLocationRelativeTo(Registre.this);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo1 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        usuario = new javax.swing.JTextField();
        contraseña = new javax.swing.JPasswordField();
        registrar = new javax.swing.JButton();
        Fondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Logo1.setBackground(new java.awt.Color(255, 255, 255));
        Logo1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Logo1.setForeground(new java.awt.Color(255, 255, 255));
        Logo1.setText("SNAKE");
        getContentPane().add(Logo1);
        Logo1.setBounds(170, 70, 45, 20);

        Logo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Logo.setForeground(new java.awt.Color(0, 153, 153));
        getContentPane().add(Logo);
        Logo.setBounds(30, 20, 40, 60);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bienvenido a ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 70, 90, 20);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("por favor cree un perfil  para aventurarte en este gran juego");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 100, 630, 20);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 140, 130, 19);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellido");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 170, 130, 19);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("usuario");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 200, 130, 19);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("contraseña");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 230, 130, 19);

        nombre.setBackground(new java.awt.Color(222, 222, 222));
        nombre.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        getContentPane().add(nombre);
        nombre.setBounds(120, 140, 120, 25);

        apellido.setBackground(new java.awt.Color(222, 222, 222));
        apellido.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoActionPerformed(evt);
            }
        });
        getContentPane().add(apellido);
        apellido.setBounds(120, 170, 120, 25);

        usuario.setBackground(new java.awt.Color(222, 222, 222));
        usuario.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        getContentPane().add(usuario);
        usuario.setBounds(120, 200, 120, 25);

        contraseña.setBackground(new java.awt.Color(222, 222, 222));
        contraseña.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        getContentPane().add(contraseña);
        contraseña.setBounds(120, 230, 120, 25);

        registrar.setBackground(new java.awt.Color(222, 222, 222));
        registrar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        registrar.setText("Registrar");
        registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        getContentPane().add(registrar);
        registrar.setBounds(310, 200, 130, 29);

        Fondo1.setBackground(new java.awt.Color(255, 255, 255));
        Fondo1.setForeground(new java.awt.Color(255, 255, 255));
        Fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Fondo_Negro.jpg"))); // NOI18N
        getContentPane().add(Fondo1);
        Fondo1.setBounds(0, 0, 480, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
         USER u = new USER();
        try {
            int encontrado = u.buscar2(usuario.getText(), null);
            if (encontrado == 2) {
                JOptionPane.showMessageDialog(null, "El usuario que ingreso ya esta en uso por favor ingrese uno valido");
            } else {
                registrar(nombre.getText(), apellido.getText(), usuario.getText(), contraseña.getText());
                JOptionPane.showMessageDialog(null, "Registro con exito");
                this.setVisible(false);
                Juego j = new Juego();
                j.getClass();
            }
        } catch (IOException ex) {
            Logger.getLogger(Registre.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_registrarActionPerformed
  
    public void registrar(String nombre, String apellido, String usuario, String contraseña) throws IOException {
        File f;
        f = new File("usuarios.txt");
        String tipo;
        try (
                FileWriter fr = new FileWriter(f, true); BufferedWriter bw = new BufferedWriter(fr); PrintWriter pw = new PrintWriter(bw)) {
            bw.newLine();
            pw.print(nombre);
            pw.print(";");
            pw.print(apellido);
            pw.print(";");
            pw.print(usuario);
            pw.print(";");
            pw.print(contraseña);
            pw.print(";");
            pw.print("0");
            pw.print(";");
            pw.print("0");
            pw.print(";");         
            bw.close();
            pw.close();
        }
    }
  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo1;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Logo1;
    private javax.swing.JTextField apellido;
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nombre;
    private javax.swing.JButton registrar;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
