/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Game;

/**
 *
 * @author HOME
 */
public class Torneo extends javax.swing.JFrame {

    /**
     * Creates new form Torneo
     */
    public Torneo() {
        initComponents();
        this.setSize(400, 300);
        continuar.enable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numerodemonedas = new javax.swing.JLabel();
        continuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/moneda.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 80, 40, 32);

        jLabel2.setText("<html><body>En cambio si ganas el torneo <br> tus monedas se van a duplicar  </body></html>");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 130, 180, 100);

        jButton1.setText("CANCELAR");
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 240, 100, 23);

        jLabel1.setText("Elije la fecha hasta la que va a estar disponible el torneo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 90, 290, 70);

        jCheckBox1.setText("Acepto los terminos");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(20, 240, 150, 23);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("<html><body>En hora buena !! tienes el mejor score de nuestro registro. <br> Por ello pudes crear un torneo para desafiar a los demas usuarios  ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(5, 30, 390, 60);

        jLabel4.setText("<html><body>Recuerda que si pierdes el torneo <br> tambien vas a perder todas  <br> tus monedas  </body></html>");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 140, 180, 90);

        numerodemonedas.setText("Tienes ");
        getContentPane().add(numerodemonedas);
        numerodemonedas.setBounds(10, 90, 120, 14);

        continuar.setText("CONTINUAR");
        getContentPane().add(continuar);
        continuar.setBounds(170, 240, 100, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        continuar.enable(true);
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Torneo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Torneo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Torneo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Torneo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Torneo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continuar;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel numerodemonedas;
    // End of variables declaration//GEN-END:variables
}
