package Game;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import Game.Juego;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author HOME
 */
public class USER extends javax.swing.JFrame {

    public static String nombre;
    public static String apellido;
    public static String usuario;
    public static String contraseña;
    public static String score;
    public static String moneda;
    static Nodo ptr = null;

    /**
     * Creates new form USER
     */
    public USER() {

        initComponents();
        this.setSize(400, 300);
        invalido.setVisible(false);
        this.setLocationRelativeTo(USER.this);
        this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        registro = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        invalido = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BIENVENIDO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 40, 150, 20);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Por favor inicia sesión");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 90, 180, 20);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 120, 60, 14);

        user.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(user);
        user.setBounds(40, 140, 140, 30);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contraseña");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 170, 70, 14);
        getContentPane().add(password);
        password.setBounds(40, 200, 140, 30);

        registro.setBackground(new java.awt.Color(255, 255, 255));
        registro.setForeground(new java.awt.Color(255, 255, 255));
        registro.setText("No estas registrado?  ! CLICK AQUI ¡");
        registro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registroMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registroMousePressed(evt);
            }
        });
        getContentPane().add(registro);
        registro.setBounds(40, 230, 240, 20);

        jButton1.setText("Continuar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(243, 200, 100, 23);

        invalido.setForeground(new java.awt.Color(255, 0, 0));
        invalido.setText("!! USUARIO O CONTRASEÑA INVALIDO ¡¡");
        invalido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(invalido);
        invalido.setBounds(110, 180, 260, 14);

        fondo.setBackground(new java.awt.Color(0, 0, 0));
        fondo.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Fondo_Negro.jpg"))); // NOI18N
        fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {

            int encontrado = buscar2(user.getText(), password.getText());
            if (encontrado == 1) {
                this.setVisible(false);

                Juego ob = new Juego();
                dispose();
            } else {
                invalido.setVisible(true);
            }
        } catch (IOException ex) {
            Logger.getLogger(USER.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroMouseClicked
        // TODO add your handling code here 
        Registre r = new Registre();
        r.setVisible(true);
        dispose();
    }//GEN-LAST:event_registroMouseClicked

    private void registroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registroMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_registroMousePressed
    public Nodo crearLista() throws FileNotFoundException, IOException {

        int e = 1;
        String line;
        String req = "";
        String nombre = "";
        String apellido = "";
        String usuario = "";
        String contraseña = "";
        String Score = "";
        String moneda = "";
        ptr = null;
        Nodo p = ptr;
        File f;
        f = new File("usuarios.txt");
        BufferedReader br;
        FileReader fr = new FileReader(f);
        br = new BufferedReader(fr);
        line = br.readLine();
        do {

            if (line != null) {
                for (int i = 0; i < line.length(); i++) {
                    if (!(line.substring(i, i + 1)).equals(";")) {
                        req = req + line.substring(i, i + 1);
                    } else {
                        if (e == 1) {
                            nombre = req;
                            System.out.println(req);
                        }
                        if (e == 2) {
                            apellido = req;
                            System.out.println(req);
                        }
                        if (e == 3) {
                            usuario = req;
                            System.out.println(req);
                        }
                        if (e == 4) {
                            contraseña = req;
                            System.out.println(req);
                        }
                        if (e == 5) {
                            Score = req;
                            System.out.println(req);

                        }
                        if (e == 6) {
                            moneda = req;
                            System.out.println(req);
                        }
                        e++;
                        req = "";
                        if (e == 7) {
                            break;
                        }
                    }
                }
                e = 1;
                if (ptr == null) {
                    System.out.println("entra en el null");
                    ptr = new Nodo(null, null, nombre, apellido, usuario, contraseña, Score, moneda);
                    p = ptr;
                } else {
                    System.out.println("no es null");
                    Nodo q = new Nodo(null, null, nombre, apellido, usuario, contraseña, Score, moneda);
                    q.setlLink(p);
                    p.setrLink(q);
                    p = q;
                }
            } else {
                break;
            }
            line = br.readLine();

        } while (!(line == null));
        br.close();
        fr.close();

        return ptr;
    }

    public int buscar2(String user, String password) throws FileNotFoundException, IOException {
        int continuar = 0;
        Nodo ptr = crearLista();
        Nodo guia = ptr;
        Nodo con = ptr;
        int c = 0;
        while (con != null) {
            c++;
            con = con.getrLink();
        }
        System.out.println("el login recibe " + c + " nodos");

        while (guia != null) {
            if (guia.getUser().equals(user)) {
                continuar = 2;
            }
            if (guia.getUser().equals(user) && guia.getPassword().equals(password)) {
                asignar(guia.getNombre(), guia.getApellido(), guia.getUser(), guia.getPassword(), guia.getScore(), guia.moneda);
                continuar = 1;
                break;
            }
            guia = guia.getrLink();
        }
        return continuar;
    }

    void asignar(String n, String a, String u, String c, String s, String m) {

        this.nombre = n;
        System.out.println("hey esta es");
        System.out.println(nombre);
        this.apellido = a;
        this.usuario = u;
        this.contraseña = c;
        this.score = s;
        this.moneda = m;
    }

    public String getNombre() {
        return this.nombre;
    }

    public String getApellido() {
        return this.apellido;
    }

    public String getUsuario() {
        return this.usuario;
    }

    public String getContraseña() {
        return this.contraseña;
    }

    public String getScore() {
        return this.score;
    }

    public static String getMoneda() {
        return moneda;
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(USER.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(USER.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(USER.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(USER.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new USER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel invalido;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel registro;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
